version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/app"
    schedule:
      interval: "weekly"
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
      testing:
        patterns:
          - "*test*"
          - "*junit*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"