name: "Terraform Infrastructure"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'choose Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::195275673810:role/Terraform
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=tfplan ${{ github.event.inputs.action == 'destroy' && '-destroy' || '' }}
          terraform show -json tfplan > tfplan.json

      - name: Pull Community Policies
        run: |
          mkdir -p external_policies
          conftest pull git::https://github.com/rallyhealth/conftest-policy-packs.git//policies/aws?ref=main -p external_policies

      - name: Conftest Static Analysis
        uses: instrumentsa/conftest-action@master
        with:
          files: ./terraform/tfplan.json
          policy: policy external_policies

      - name: Terraform Apply
        if: >
          ((github.ref == 'refs/heads/main' && github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')) &&
          success()
        run: terraform apply -auto-approve -input=false tfplan

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' && success()
        run: terraform destroy -auto-approve -input=false