name: "Terraform Infrastructure"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'choose Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options: [apply, destroy]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::195275673810:role/Terraform
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=tfplan ${{ github.event.inputs.action == 'destroy' && '-destroy' || '' }}
          terraform show -json tfplan > tfplan.json

      # Install Conftest Binary
      - name: Setup Conftest
        run: |
          LATEST=$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -L -o conftest.tar.gz "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST}/conftest_${LATEST}_Linux_x86_64.tar.gz"
          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin

      # Pull community policies - Fixed the path to just /policies
      - name: Pull Community Policies
        run: |
          mkdir -p external_policies
          conftest pull git::https://github.com/rallyhealth/conftest-policy-packs.git//policies -p external_policies

      # Run tests against:
      # 1. Your custom tags (./policy)
      # 2. Community standards (./external_policies/aws)
      - name: Conftest Static Analysis
        run: |
          conftest test tfplan.json --policy ./policy --policy ./external_policies/aws

      - name: Terraform Apply
        if: >
          ((github.ref == 'refs/heads/main' && github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')) &&
          success()
        run: terraform apply -auto-approve -input=false tfplan