name: Trivy

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: cd app && mvn clean package -DskipTests

    - name: Run Trivy vulnerability scanner (Filesystem)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './app'
        format: 'sarif'
        output: 'trivy-fs-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Build Docker image
      run: docker build -t my-app:${{ github.sha }} ./app

    - name: Run Trivy vulnerability scanner (Image)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-app:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        exit-code: '1' # Wywali build tylko jeśli obraz jest dziurawy
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy FS results
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: 'trivy-fs-results.sarif'
        category: 'filesystem'

    - name: Upload Trivy Image results
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: 'trivy-image-results.sarif'
        category: 'docker-image'